// @see https://w3c.github.io/ServiceWorker/#client-interface

[Exposed=ServiceWorker]
interface Client {
	readonly attribute USVString url;
	readonly attribute DOMString id;
	readonly attribute ClientType type;
	readonly attribute boolean reserved;
	void postMessage(any message, optional sequence<object> transfer = []);
};

[Exposed=ServiceWorker]
interface WindowClient : Client {
	readonly attribute VisibilityState visibilityState;
	readonly attribute boolean focused;
	[SameObject] readonly attribute FrozenArray<USVString> ancestorOrigins;
	[NewObject] Promise<WindowClient> focus();
	[NewObject] Promise<WindowClient> navigate(USVString url);
};
