// @see https://w3c.github.io/ServiceWorker/#clients-interface

[Exposed=ServiceWorker]
interface Clients {
	// The objects returned will be new instances every time
	[NewObject] Promise<any> get(DOMString id);
	[NewObject] Promise<sequence<Client>> matchAll(optional ClientQueryOptions options);
	[NewObject] Promise<WindowClient?> openWindow(USVString url);
	[NewObject] Promise<void> claim();
};
dictionary ClientQueryOptions {
	boolean includeUncontrolled = false;
	boolean includeReserved = false;
	ClientType type = "window";
};
enum ClientType {
	"window",
	"worker",
	"sharedworker",
	"all"
};
