// @see https://github.com/whatwg/fetch/issues/447#issuecomment-281731850

[Constructor(), Exposed=(Window,Worker)]
interface FetchController {
	readonly attribute FetchSignal signal;

	void setPriority(octet priority);
	void abort();
	void follow(FetchSignal signal);
	void unfollow(FetchSignal signal);
};

dictionary RequestInit {
	FetchSignal signal;
};

[Exposed=(Window,Worker)]
interface FetchSignal : EventTarget {
	readonly attribute octet priority;
	readonly attribute boolean aborted;

	attribute EventHandler onabort;
	attribute EventHandler onprioritychange;
};
