// @see https://w3c.github.io/ServiceWorker/#fetchevent-interface

[Constructor(DOMString type, FetchEventInit eventInitDict), Exposed=ServiceWorker]
interface FetchEvent : ExtendableEvent {
	[SameObject] readonly attribute Request request;
	readonly attribute Promise<any> preloadResponse;
	readonly attribute DOMString clientId;
	readonly attribute DOMString reservedClientId;
	readonly attribute DOMString targetClientId;

	void respondWith(Promise<Response> r);
};
dictionary FetchEventInit : ExtendableEventInit {
	required Request request;
	required Promise<any> preloadResponse;
	DOMString clientId = "";
	DOMString reservedClientId = "";
	DOMString targetClientId = "";
};
