// @see https://w3c.github.io/ServiceWorker/#foreignfetchevent-interface

[Constructor(DOMString type, ForeignFetchEventInit eventInitDict), Exposed=ServiceWorker]
interface ForeignFetchEvent : ExtendableEvent {
	[SameObject] readonly attribute Request request;
	readonly attribute USVString origin;

	void respondWith(Promise<ForeignFetchResponse> r);
};

dictionary ForeignFetchEventInit : ExtendableEventInit {
	required Request request;
	USVString origin = "null";
};

dictionary ForeignFetchResponse {
	required Response response;
	USVString origin;
	sequence<ByteString> headers;
};
