// @see https://w3c.github.io/ServiceWorker/#installevent-interface

[Constructor(DOMString type, optional ExtendableEventInit eventInitDict), Exposed=ServiceWorker]
interface InstallEvent : ExtendableEvent {
	void registerForeignFetch(ForeignFetchOptions options);
};

dictionary ForeignFetchOptions {
	required sequence<USVString> scopes;
	required sequence<USVString> origins;
};
