// @see https://w3c.github.io/ServiceWorker/#navigation-preload-manager

[SecureContext, Exposed=(Window,Worker)]
interface NavigationPreloadManager {
	Promise<void> enable();
	Promise<void> disable();
	Promise<void> setHeaderValue(ByteString value);
	Promise<NavigationPreloadState> getState();
};

dictionary NavigationPreloadState {
	boolean enabled = false;
	ByteString headerValue;
};
