// @see https://w3c.github.io/ServiceWorker/#serviceworkerregistration-interface

[SecureContext, Exposed=(Window,Worker)]
interface ServiceWorkerRegistration : EventTarget {
	readonly attribute ServiceWorker? installing;
	readonly attribute ServiceWorker? waiting;
	readonly attribute ServiceWorker? active;
	readonly attribute NavigationPreloadManager navigationPreload;

	readonly attribute USVString scope;
	readonly attribute boolean useCache;

	[NewObject] Promise<void> update();
	[NewObject] Promise<boolean> unregister();

	// event
	attribute EventHandler onupdatefound;
};
